const PROFILES = {
  "chloe-love": {
    first: "Chloe", last: "Love",
    cities: "London / Berlin / Paris",
    height: "172", heightImp: "5'8\"",
    dress: "34", dressImp: "4 / XS",
    shoes: "38", shoesImp: "7.5",
    bust: "82", bustImp: "32\"",
    waist: "61", waistImp: "24\"",
    hips: "89", hipsImp: "35\"",
    board: "women",
    cover: "images/chloe-love-cover.jpg",
    gallery: ["Editorial","Studio","Beauty","Outdoor","Portrait","Fashion","Studio","Campaign","Editorial","Beauty","Studio","Outdoor"]
  },
  "maren-voss": {
    first: "Maren", last: "Voss",
    cities: "Berlin / New York / Paris",
    height: "178", heightImp: "5'10\"",
    dress: "34", dressImp: "4 / XS",
    shoes: "41", shoesImp: "10",
    bust: "83", bustImp: "33\"",
    waist: "65", waistImp: "26\"",
    hips: "92", hipsImp: "36\"",
    board: "women",
    cover: "images/maren-voss-cover.png",
    gallery: ["Editorial","Studio","Beauty","Studio","Editorial","Outdoor","Beauty","Fashion","Studio","Campaign","Portrait","Outdoor"]
  },
  "lina-berger": {
    first: "Lina", last: "Berger",
    cities: "Berlin / Hamburg",
    height: "180", heightImp: "5'11\"",
    dress: "36", dressImp: "6 / S",
    shoes: "40", shoesImp: "9",
    bust: "85", bustImp: "33.5\"",
    waist: "64", waistImp: "25\"",
    hips: "91", hipsImp: "36\"",
    board: "women",
    cover: "images/lina-berger-cover.png",
    gallery: ["Portrait","Studio","Beauty","Outdoor","Editorial","Studio","Beauty","Fashion","Campaign","Studio","Portrait","Editorial"]
  },
  "sanne-de-vries": {
    first: "Sanne", last: "de Vries",
    cities: "Amsterdam / Berlin",
    height: "177", heightImp: "5'9.5\"",
    dress: "36", dressImp: "6 / S",
    shoes: "39", shoesImp: "8.5",
    bust: "84", bustImp: "33\"",
    waist: "66", waistImp: "26\"",
    hips: "93", hipsImp: "36.5\"",
    board: "women",
    cover: "images/sanne-de-vries-cover.png",
    gallery: ["Studio","Editorial","Outdoor","Beauty","Studio","Portrait","Fashion","Editorial","Beauty","Campaign","Studio","Outdoor"]
  },
  "isla-novak": {
    first: "Isla", last: "Novak",
    cities: "Prague / Berlin / Milan",
    height: "175", heightImp: "5'9\"",
    dress: "34", dressImp: "4 / XS",
    shoes: "39", shoesImp: "8.5",
    bust: "82", bustImp: "32\"",
    waist: "62", waistImp: "24.5\"",
    hips: "90", hipsImp: "35.5\"",
    board: "women",
    cover: "images/isla-novak-cover.png",
    gallery: ["Beauty","Studio","Editorial","Outdoor","Portrait","Studio","Fashion","Editorial","Beauty","Studio","Campaign","Outdoor"]
  },
  "aya-kimura": {
    first: "Aya", last: "Kimura",
    cities: "Tokyo / Berlin / Paris",
    height: "174", heightImp: "5'8.5\"",
    dress: "34", dressImp: "4 / XS",
    shoes: "38", shoesImp: "7.5",
    bust: "80", bustImp: "31.5\"",
    waist: "60", waistImp: "23.5\"",
    hips: "88", hipsImp: "34.5\"",
    board: "women",
    cover: "images/aya-kimura-cover.png",
    gallery: ["Editorial","Beauty","Studio","Fashion","Outdoor","Portrait","Studio","Editorial","Beauty","Campaign","Studio","Outdoor"]
  },
  "clara-stein": {
    first: "Clara", last: "Stein",
    cities: "Munich / Berlin",
    height: "179", heightImp: "5'10.5\"",
    dress: "36", dressImp: "6 / S",
    shoes: "40", shoesImp: "9",
    bust: "86", bustImp: "34\"",
    waist: "66", waistImp: "26\"",
    hips: "93", hipsImp: "36.5\"",
    board: "women",
    cover: "images/clara-stein-cover.png",
    gallery: ["Studio","Portrait","Editorial","Beauty","Outdoor","Fashion","Studio","Editorial","Beauty","Campaign","Portrait","Studio"]
  },
  "noor-el-amin": {
    first: "Noor", last: "El-Amin",
    cities: "Berlin / London",
    height: "176", heightImp: "5'9\"",
    dress: "34", dressImp: "4 / XS",
    shoes: "39", shoesImp: "8.5",
    bust: "83", bustImp: "33\"",
    waist: "63", waistImp: "25\"",
    hips: "90", hipsImp: "35.5\"",
    board: "women",
    cover: "images/noor-el-amin-cover.png",
    gallery: ["Editorial","Studio","Beauty","Fashion","Portrait","Outdoor","Studio","Editorial","Campaign","Beauty","Studio","Outdoor"]
  },
  "petra-holst": {
    first: "Petra", last: "Holst",
    cities: "Copenhagen / Berlin",
    height: "181", heightImp: "5'11\"",
    dress: "36", dressImp: "6 / S",
    shoes: "41", shoesImp: "10",
    bust: "85", bustImp: "33.5\"",
    waist: "67", waistImp: "26.5\"",
    hips: "94", hipsImp: "37\"",
    board: "women",
    cover: "images/petra-holst-cover.png",
    gallery: ["Outdoor","Studio","Editorial","Beauty","Portrait","Fashion","Studio","Campaign","Editorial","Beauty","Studio","Outdoor"]
  },
  "zola-mbeki": {
    first: "Zola", last: "Mbeki",
    cities: "Johannesburg / Berlin",
    height: "177", heightImp: "5'9.5\"",
    dress: "36", dressImp: "6 / S",
    shoes: "40", shoesImp: "9",
    bust: "86", bustImp: "34\"",
    waist: "68", waistImp: "27\"",
    hips: "95", hipsImp: "37.5\"",
    board: "women",
    cover: "images/zola-mbeki-cover.png",
    gallery: ["Studio","Editorial","Beauty","Portrait","Outdoor","Fashion","Campaign","Studio","Editorial","Beauty","Studio","Outdoor"]
  },
  "vera-lindgren": {
    first: "Vera", last: "Lindgren",
    cities: "Stockholm / Berlin",
    height: "182", heightImp: "6'0\"",
    dress: "36", dressImp: "6 / S",
    shoes: "41", shoesImp: "10",
    bust: "84", bustImp: "33\"",
    waist: "65", waistImp: "25.5\"",
    hips: "92", hipsImp: "36\"",
    board: "women",
    cover: "images/vera-lindgren-cover.png",
    gallery: ["Portrait","Editorial","Studio","Beauty","Fashion","Outdoor","Campaign","Studio","Editorial","Beauty","Studio","Outdoor"]
  },
  "mila-roux": {
    first: "Mila", last: "Roux",
    cities: "Paris / Berlin",
    height: "176", heightImp: "5'9\"",
    dress: "34", dressImp: "4 / XS",
    shoes: "39", shoesImp: "8.5",
    bust: "82", bustImp: "32.5\"",
    waist: "62", waistImp: "24.5\"",
    hips: "89", hipsImp: "35\"",
    board: "women",
    cover: "images/mila-roux-cover.png",
    gallery: ["Editorial","Beauty","Studio","Outdoor","Portrait","Fashion","Studio","Campaign","Editorial","Beauty","Studio","Outdoor"]
  },
  "freya-brandt": {
    first: "Freya", last: "Brandt",
    cities: "Berlin / Hamburg",
    height: "178", heightImp: "5'10\"",
    dress: "36", dressImp: "6 / S",
    shoes: "40", shoesImp: "9",
    bust: "85", bustImp: "33.5\"",
    waist: "66", waistImp: "26\"",
    hips: "93", hipsImp: "36.5\"",
    board: "women",
    cover: "images/freya-brandt-cover.png",
    gallery: ["Studio","Editorial","Beauty","Fashion","Outdoor","Portrait","Campaign","Studio","Editorial","Beauty","Outdoor","Studio"]
  },
  "elias-roth": {
    first: "Elias", last: "Roth",
    cities: "Berlin / New York",
    height: "192", heightImp: "6'4\"",
    dress: "50", dressImp: "40 / M",
    shoes: "44", shoesImp: "11",
    bust: "98", bustImp: "38.5\"",
    waist: "80", waistImp: "31.5\"",
    hips: "95", hipsImp: "37.5\"",
    board: "men",
    gallery: ["Editorial","Studio","Outdoor","Portrait","Fashion","Studio","Campaign","Editorial","Studio","Outdoor","Portrait","Studio"]
  },
  "noel-matteo": {
    first: "Noel", last: "Matteo",
    cities: "Milan / Berlin",
    height: "190", heightImp: "6'3\"",
    dress: "50", dressImp: "40 / M",
    shoes: "43", shoesImp: "10.5",
    bust: "97", bustImp: "38\"",
    waist: "79", waistImp: "31\"",
    hips: "94", hipsImp: "37\"",
    board: "men",
    gallery: ["Studio","Editorial","Portrait","Outdoor","Fashion","Studio","Campaign","Editorial","Studio","Portrait","Outdoor","Studio"]
  },
  "viktor-orlov": {
    first: "Viktor", last: "Orlov",
    cities: "Moscow / Berlin",
    height: "188", heightImp: "6'2\"",
    dress: "48", dressImp: "38 / S",
    shoes: "43", shoesImp: "10.5",
    bust: "96", bustImp: "38\"",
    waist: "78", waistImp: "30.5\"",
    hips: "93", hipsImp: "36.5\"",
    board: "men",
    gallery: ["Portrait","Studio","Editorial","Fashion","Outdoor","Studio","Campaign","Editorial","Studio","Portrait","Outdoor","Studio"]
  },
  "andrei-orlov": {
    first: "Andrei", last: "Orlov",
    cities: "Moscow / Berlin",
    height: "188", heightImp: "6'2\"",
    dress: "48", dressImp: "38 / S",
    shoes: "43", shoesImp: "10.5",
    bust: "96", bustImp: "38\"",
    waist: "78", waistImp: "30.5\"",
    hips: "93", hipsImp: "36.5\"",
    board: "men",
    gallery: ["Editorial","Studio","Portrait","Fashion","Outdoor","Campaign","Studio","Editorial","Portrait","Studio","Outdoor","Studio"]
  },
  "kai-engstrom": {
    first: "Kai", last: "Engstr\u00f6m",
    cities: "Stockholm / Berlin",
    height: "185", heightImp: "6'1\"",
    dress: "48", dressImp: "38 / S",
    shoes: "42", shoesImp: "10",
    bust: "95", bustImp: "37.5\"",
    waist: "77", waistImp: "30\"",
    hips: "92", hipsImp: "36\"",
    board: "men",
    gallery: ["Studio","Editorial","Outdoor","Portrait","Fashion","Campaign","Studio","Editorial","Studio","Portrait","Outdoor","Studio"]
  },
  "marcus-bauer": {
    first: "Marcus", last: "Bauer",
    cities: "Berlin / Munich",
    height: "191", heightImp: "6'3\"",
    dress: "50", dressImp: "40 / M",
    shoes: "44", shoesImp: "11",
    bust: "99", bustImp: "39\"",
    waist: "81", waistImp: "32\"",
    hips: "96", hipsImp: "38\"",
    board: "men",
    gallery: ["Editorial","Studio","Portrait","Outdoor","Fashion","Studio","Campaign","Editorial","Studio","Outdoor","Portrait","Studio"]
  },
  "leo-tanaka": {
    first: "Leo", last: "Tanaka",
    cities: "Tokyo / Berlin",
    height: "183", heightImp: "6'0\"",
    dress: "48", dressImp: "38 / S",
    shoes: "42", shoesImp: "10",
    bust: "94", bustImp: "37\"",
    waist: "76", waistImp: "30\"",
    hips: "91", hipsImp: "36\"",
    board: "men",
    gallery: ["Portrait","Editorial","Studio","Fashion","Outdoor","Campaign","Studio","Editorial","Studio","Portrait","Outdoor","Studio"]
  },
  "rafael-costa": {
    first: "Rafael", last: "Costa",
    cities: "Lisbon / Berlin",
    height: "187", heightImp: "6'1.5\"",
    dress: "50", dressImp: "40 / M",
    shoes: "43", shoesImp: "10.5",
    bust: "97", bustImp: "38\"",
    waist: "79", waistImp: "31\"",
    hips: "94", hipsImp: "37\"",
    board: "men",
    gallery: ["Studio","Portrait","Editorial","Outdoor","Fashion","Campaign","Studio","Editorial","Portrait","Studio","Outdoor","Studio"]
  },
  "ines-morel": {
    first: "Ines", last: "Morel",
    cities: "Paris / Berlin",
    height: "176", heightImp: "5'9\"",
    dress: "34", dressImp: "4 / XS",
    shoes: "39", shoesImp: "8.5",
    bust: "82", bustImp: "32.5\"",
    waist: "63", waistImp: "25\"",
    hips: "90", hipsImp: "35.5\"",
    board: "women",
    gallery: ["Editorial","Studio","Beauty","Outdoor","Portrait","Fashion","Studio","Campaign","Editorial","Beauty","Studio","Outdoor"]
  },
  "tobias-falk": {
    first: "Tobias", last: "Falk",
    cities: "Berlin / Hamburg",
    height: "189", heightImp: "6'2\"",
    dress: "50", dressImp: "40 / M",
    shoes: "44", shoesImp: "11",
    bust: "97", bustImp: "38\"",
    waist: "80", waistImp: "31.5\"",
    hips: "94", hipsImp: "37\"",
    board: "women",
    gallery: ["Studio","Editorial","Portrait","Outdoor","Fashion","Campaign","Studio","Editorial","Studio","Portrait","Outdoor","Studio"]
  },
  "yara-osman": {
    first: "Yara", last: "Osman",
    cities: "Berlin / London",
    height: "174", heightImp: "5'8.5\"",
    dress: "34", dressImp: "4 / XS",
    shoes: "38", shoesImp: "7.5",
    bust: "81", bustImp: "32\"",
    waist: "62", waistImp: "24.5\"",
    hips: "89", hipsImp: "35\"",
    board: "women",
    gallery: ["Beauty","Studio","Editorial","Outdoor","Portrait","Fashion","Studio","Campaign","Editorial","Beauty","Studio","Outdoor"]
  },
  "finn-larsen": {
    first: "Finn", last: "Larsen",
    cities: "Copenhagen / Berlin",
    height: "186", heightImp: "6'1\"",
    dress: "48", dressImp: "38 / S",
    shoes: "43", shoesImp: "10.5",
    bust: "95", bustImp: "37.5\"",
    waist: "78", waistImp: "30.5\"",
    hips: "93", hipsImp: "36.5\"",
    board: "women",
    gallery: ["Editorial","Studio","Outdoor","Portrait","Fashion","Campaign","Studio","Editorial","Studio","Portrait","Outdoor","Studio"]
  },
  "amara-diallo": {
    first: "Amara", last: "Diallo",
    cities: "Dakar / Berlin / Paris",
    height: "178", heightImp: "5'10\"",
    dress: "36", dressImp: "6 / S",
    shoes: "40", shoesImp: "9",
    bust: "84", bustImp: "33\"",
    waist: "65", waistImp: "25.5\"",
    hips: "92", hipsImp: "36\"",
    board: "women",
    gallery: ["Studio","Editorial","Beauty","Outdoor","Portrait","Fashion","Campaign","Studio","Editorial","Beauty","Outdoor","Studio"]
  },
  "luca-weiss": {
    first: "Luca", last: "Weiss",
    cities: "Berlin / Zurich",
    height: "184", heightImp: "6'0.5\"",
    dress: "48", dressImp: "38 / S",
    shoes: "42", shoesImp: "10",
    bust: "94", bustImp: "37\"",
    waist: "77", waistImp: "30\"",
    hips: "92", hipsImp: "36\"",
    board: "women",
    gallery: ["Portrait","Studio","Editorial","Outdoor","Fashion","Campaign","Studio","Editorial","Studio","Portrait","Outdoor","Studio"]
  },
  "sofie-kjaer": {
    first: "Sofie", last: "Kjaer",
    cities: "Copenhagen / Berlin",
    height: "175", heightImp: "5'9\"",
    dress: "34", dressImp: "4 / XS",
    shoes: "39", shoesImp: "8.5",
    bust: "82", bustImp: "32.5\"",
    waist: "63", waistImp: "25\"",
    hips: "90", hipsImp: "35.5\"",
    board: "women",
    gallery: ["Editorial","Beauty","Studio","Outdoor","Portrait","Fashion","Campaign","Studio","Editorial","Beauty","Studio","Outdoor"]
  },
  "rami-haddad": {
    first: "Rami", last: "Haddad",
    cities: "Beirut / Berlin",
    height: "187", heightImp: "6'1.5\"",
    dress: "50", dressImp: "40 / M",
    shoes: "43", shoesImp: "10.5",
    bust: "96", bustImp: "38\"",
    waist: "79", waistImp: "31\"",
    hips: "94", hipsImp: "37\"",
    board: "women",
    gallery: ["Studio","Editorial","Portrait","Outdoor","Fashion","Campaign","Studio","Editorial","Portrait","Studio","Outdoor","Studio"]
  },
  "carla-voss": {
    first: "Carla", last: "Voss",
    cities: "Berlin / Hamburg",
    height: "180", heightImp: "5'11\"",
    dress: "42", dressImp: "12 / L",
    shoes: "41", shoesImp: "10",
    bust: "100", bustImp: "39.5\"",
    waist: "78", waistImp: "30.5\"",
    hips: "108", hipsImp: "42.5\"",
    board: "curved",
    gallery: ["Editorial","Studio","Beauty","Fashion","Outdoor","Portrait","Campaign","Studio","Editorial","Beauty","Studio","Outdoor"]
  },
  "leonie-schulz": {
    first: "Leonie", last: "Schulz",
    cities: "Berlin / Cologne",
    height: "175", heightImp: "5'9\"",
    dress: "42", dressImp: "12 / L",
    shoes: "40", shoesImp: "9",
    bust: "98", bustImp: "38.5\"",
    waist: "76", waistImp: "30\"",
    hips: "106", hipsImp: "41.5\"",
    board: "curved",
    gallery: ["Studio","Editorial","Beauty","Outdoor","Portrait","Fashion","Campaign","Studio","Editorial","Beauty","Outdoor","Studio"]
  },
  "aisha-rahman": {
    first: "Aisha", last: "Rahman",
    cities: "London / Berlin",
    height: "172", heightImp: "5'8\"",
    dress: "40", dressImp: "10 / M",
    shoes: "39", shoesImp: "8.5",
    bust: "96", bustImp: "38\"",
    waist: "75", waistImp: "29.5\"",
    hips: "104", hipsImp: "41\"",
    board: "curved",
    gallery: ["Beauty","Studio","Editorial","Fashion","Outdoor","Portrait","Campaign","Studio","Editorial","Beauty","Studio","Outdoor"]
  },
  "bianca-ferro": {
    first: "Bianca", last: "Ferro",
    cities: "Milan / Berlin",
    height: "176", heightImp: "5'9\"",
    dress: "42", dressImp: "12 / L",
    shoes: "40", shoesImp: "9",
    bust: "99", bustImp: "39\"",
    waist: "77", waistImp: "30\"",
    hips: "107", hipsImp: "42\"",
    board: "curved",
    gallery: ["Editorial","Beauty","Studio","Outdoor","Portrait","Fashion","Campaign","Studio","Editorial","Beauty","Outdoor","Studio"]
  },
  "thandi-nkosi": {
    first: "Thandi", last: "Nkosi",
    cities: "Cape Town / Berlin",
    height: "174", heightImp: "5'8.5\"",
    dress: "40", dressImp: "10 / M",
    shoes: "39", shoesImp: "8.5",
    bust: "97", bustImp: "38\"",
    waist: "76", waistImp: "30\"",
    hips: "105", hipsImp: "41.5\"",
    board: "curved",
    gallery: ["Studio","Editorial","Beauty","Fashion","Outdoor","Portrait","Campaign","Editorial","Studio","Beauty","Outdoor","Studio"]
  },
  "eva-nordstrom": {
    first: "Eva", last: "Nordstr\u00f6m",
    cities: "Stockholm / Berlin",
    height: "178", heightImp: "5'10\"",
    dress: "42", dressImp: "12 / L",
    shoes: "41", shoesImp: "10",
    bust: "100", bustImp: "39.5\"",
    waist: "78", waistImp: "30.5\"",
    hips: "108", hipsImp: "42.5\"",
    board: "curved",
    gallery: ["Portrait","Studio","Editorial","Beauty","Fashion","Outdoor","Campaign","Studio","Editorial","Beauty","Studio","Outdoor"]
  }
};

// Helper: get slug from full name
function nameToSlug(name) {
  return name.toLowerCase()
    .replace(/\u00f6/g, 'o').replace(/\u00e9/g, 'e').replace(/\u00e4/g, 'a').replace(/\u00fc/g, 'u')
    .replace(/&amp;/g, '').replace(/&/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}
